# CMake generated Testfile for 
# Source directory: C:/Users/Mark/OneDrive/Desktop/ReLimiter v3/tests
# Build directory: C:/Users/Mark/OneDrive/Desktop/ReLimiter v3/build32/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[dmfg_detection_properties]=] "C:/Users/Mark/OneDrive/Desktop/ReLimiter v3/build32/bin/Debug/test_dmfg_detection.exe")
  set_tests_properties([=[dmfg_detection_properties]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Mark/OneDrive/Desktop/ReLimiter v3/tests/CMakeLists.txt;37;add_test;C:/Users/Mark/OneDrive/Desktop/ReLimiter v3/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[dmfg_detection_properties]=] "C:/Users/Mark/OneDrive/Desktop/ReLimiter v3/build32/bin/Release/test_dmfg_detection.exe")
  set_tests_properties([=[dmfg_detection_properties]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Mark/OneDrive/Desktop/ReLimiter v3/tests/CMakeLists.txt;37;add_test;C:/Users/Mark/OneDrive/Desktop/ReLimiter v3/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[dmfg_detection_properties]=] "C:/Users/Mark/OneDrive/Desktop/ReLimiter v3/build32/bin/MinSizeRel/test_dmfg_detection.exe")
  set_tests_properties([=[dmfg_detection_properties]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Mark/OneDrive/Desktop/ReLimiter v3/tests/CMakeLists.txt;37;add_test;C:/Users/Mark/OneDrive/Desktop/ReLimiter v3/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[dmfg_detection_properties]=] "C:/Users/Mark/OneDrive/Desktop/ReLimiter v3/build32/bin/RelWithDebInfo/test_dmfg_detection.exe")
  set_tests_properties([=[dmfg_detection_properties]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Mark/OneDrive/Desktop/ReLimiter v3/tests/CMakeLists.txt;37;add_test;C:/Users/Mark/OneDrive/Desktop/ReLimiter v3/tests/CMakeLists.txt;0;")
else()
  add_test([=[dmfg_detection_properties]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[scheduler_passthrough]=] "C:/Users/Mark/OneDrive/Desktop/ReLimiter v3/build32/bin/Debug/test_scheduler_passthrough.exe")
  set_tests_properties([=[scheduler_passthrough]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Mark/OneDrive/Desktop/ReLimiter v3/tests/CMakeLists.txt;38;add_test;C:/Users/Mark/OneDrive/Desktop/ReLimiter v3/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[scheduler_passthrough]=] "C:/Users/Mark/OneDrive/Desktop/ReLimiter v3/build32/bin/Release/test_scheduler_passthrough.exe")
  set_tests_properties([=[scheduler_passthrough]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Mark/OneDrive/Desktop/ReLimiter v3/tests/CMakeLists.txt;38;add_test;C:/Users/Mark/OneDrive/Desktop/ReLimiter v3/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[scheduler_passthrough]=] "C:/Users/Mark/OneDrive/Desktop/ReLimiter v3/build32/bin/MinSizeRel/test_scheduler_passthrough.exe")
  set_tests_properties([=[scheduler_passthrough]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Mark/OneDrive/Desktop/ReLimiter v3/tests/CMakeLists.txt;38;add_test;C:/Users/Mark/OneDrive/Desktop/ReLimiter v3/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[scheduler_passthrough]=] "C:/Users/Mark/OneDrive/Desktop/ReLimiter v3/build32/bin/RelWithDebInfo/test_scheduler_passthrough.exe")
  set_tests_properties([=[scheduler_passthrough]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Mark/OneDrive/Desktop/ReLimiter v3/tests/CMakeLists.txt;38;add_test;C:/Users/Mark/OneDrive/Desktop/ReLimiter v3/tests/CMakeLists.txt;0;")
else()
  add_test([=[scheduler_passthrough]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[dmfg_output_cap_properties]=] "C:/Users/Mark/OneDrive/Desktop/ReLimiter v3/build32/bin/Debug/test_dmfg_output_cap.exe")
  set_tests_properties([=[dmfg_output_cap_properties]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Mark/OneDrive/Desktop/ReLimiter v3/tests/CMakeLists.txt;39;add_test;C:/Users/Mark/OneDrive/Desktop/ReLimiter v3/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[dmfg_output_cap_properties]=] "C:/Users/Mark/OneDrive/Desktop/ReLimiter v3/build32/bin/Release/test_dmfg_output_cap.exe")
  set_tests_properties([=[dmfg_output_cap_properties]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Mark/OneDrive/Desktop/ReLimiter v3/tests/CMakeLists.txt;39;add_test;C:/Users/Mark/OneDrive/Desktop/ReLimiter v3/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[dmfg_output_cap_properties]=] "C:/Users/Mark/OneDrive/Desktop/ReLimiter v3/build32/bin/MinSizeRel/test_dmfg_output_cap.exe")
  set_tests_properties([=[dmfg_output_cap_properties]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Mark/OneDrive/Desktop/ReLimiter v3/tests/CMakeLists.txt;39;add_test;C:/Users/Mark/OneDrive/Desktop/ReLimiter v3/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[dmfg_output_cap_properties]=] "C:/Users/Mark/OneDrive/Desktop/ReLimiter v3/build32/bin/RelWithDebInfo/test_dmfg_output_cap.exe")
  set_tests_properties([=[dmfg_output_cap_properties]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Mark/OneDrive/Desktop/ReLimiter v3/tests/CMakeLists.txt;39;add_test;C:/Users/Mark/OneDrive/Desktop/ReLimiter v3/tests/CMakeLists.txt;0;")
else()
  add_test([=[dmfg_output_cap_properties]=] NOT_AVAILABLE)
endif()
